### ISSUE TITLE
Arcane Inscriber requires the system to contain ingredients and is incredibly laggy

### ISSUE THREAD

**Issue by mycroftjr** [Delfayne/ThaumicEnergistics#10]
**Describe the bug**
The Arcane Inscriber, which is used to program Knowledge Cores for Arcane Assemblers, currently requires you to have at least 1 of an item to insert it as part of a recipe via JEI. It should be more like the Pattern Terminal and accept ghost items instead.

Also, having the Inscriber open lags the client tremendously unless you filter the search results.

**Steps to Reproduce**
1. Right click to open the Arcane Inscriber
2. Open a recipe in JEI and click the + sign to insert it

**Expected behavior**
Items can be added to the grid with JEI regardless of whether you have them (and the Inscriber doesn't lag the client to death).

**Version Information**
 - Minecraft: 1.12.2
 - Forge: 14.23.5.2860
 - Applied Energistics: appliedenergistics2-rv6-stable-7-extended_life-v0.54.9
 - Thaumcraft: Thaumcraft-1.12.2-6.1.BETA26
 - Thaumic Energistics: thaumicenergistics-2.2.5.jar
 - Modpack: Divine Journey 2 v2.18.0

**Additional context**
On a localhost server.

**Logs/Crashlogs**
https://gist.github.com/mycroftjr/26ff34c88a5d19f1cd29ecbc32552b1b

**Comment by Delfayne** [comment]
I've applied some lag fixes elsewhere in https://github.com/Delfayne/ThaumicEnergistics/pull/35, but now I've tidied up some of the JEI handling too here https://github.com/Delfayne/ThaumicEnergistics/pull/37

**Comment by Delfayne** [comment]
Fixed in https://github.com/Delfayne/ThaumicEnergistics/releases/tag/v2.3.0
