### ISSUE TITLE
Issues with terminals in versions 2.3.0/.1

### ISSUE THREAD

**Issue by xJon** [Delfayne/ThaumicEnergistics#42]
Originally reported over https://github.com/xJon/The-1.12.2-Pack/issues/957:
> Since updating to 1.6.1 my thaumic energistics arcane and essentia terminals no longer function as they did on 1.5.6, the arcane terminal's ordering button simply doesn't work the first time around, and will reset back to A-Z every time you reopen the terminal, I also had an issue that stopped me from taking any items out of it at one point but that has since stopped and i dont know what caused it.
![2024-06-03_20 59 57](https://github.com/xJon/The-1.12.2-Pack/assets/59313384/64d2e73d-f755-4f08-abff-f3dd939768ac)
![2024-06-03_21 00 00](https://github.com/xJon/The-1.12.2-Pack/assets/59313384/afd42f2c-68f8-4341-a57f-090311519ead)
The essentia terminal no longer allows you to extract essentia with phials or jars making it quite problematic for setting up filters and research components 
![2024-06-03_20 59 49](https://github.com/xJon/The-1.12.2-Pack/assets/59313384/d226ccfa-75ed-4c29-9c57-970cbc185bfc)
![2024-06-03_21 00 13](https://github.com/xJon/The-1.12.2-Pack/assets/59313384/dcc1acbf-8230-481c-9c45-5f7c138235a2)

This appears reproducible outside the modpack environment with a minimal set of mods.

**Version Information**
 - Applied Energistics: `0.56.5`
 - Thaumic Energistics: `2.3.1`

**Comment by Delfayne** [comment]
Expecting fixed by https://github.com/Delfayne/ThaumicEnergistics/pull/46

**Comment by xJon** [comment]
@Delfayne See https://github.com/xJon/The-1.12.2-Pack/issues/957#issuecomment-2206940677

**Comment by Delfayne** [comment]
Sort order issues have since been fixed from 2.3.3
