### ISSUE TITLE
Broken Sorting in arcane crafting terminal

### ISSUE THREAD

**Issue by f1den** [Delfayne/ThaumicEnergistics#48]
**Describe the bug**
Not saving Sorting and other in arcane crafting terminal

**Steps to Reproduce**
Just click sort btn
![image](https://github.com/Delfayne/ThaumicEnergistics/assets/56506428/6e516fc7-e499-409f-90e7-bbce3a0413c9)

**Version Information**
 - Minecraft: 1.12.2
 - Forge: ?
 - Applied Energistics: 0.56.6
 - Thaumcraft: ?
 - Thaumic Energistics: 2.3.2
 - Modpack: Divine Journey 2 Custom

**Additional context**
Sorting worked in 2.2.7 (original for dj2 2.21.0)

If you can't handle fixing issues u can write me in TG: fidenexe , i will make my best to help you.

**Comment by xJon** [comment]
https://github.com/Delfayne/ThaumicEnergistics/releases/tag/v2.3.3
