### ISSUE TITLE
Arcane Terminal Autocraft Request Crash (v2.2.7)

### ISSUE THREAD

**Issue by JathTyki** [Delfayne/ThaumicEnergistics#55]
I am unsure if this has been reported or not, so I figured I would since I didn't see it in the list of issues.

**Describe the bug**
When attempting to request an autocrafting job through the Arcane Terminal, the game will completely crash.

**Steps to Reproduce**
1. Go to Arcane Terminal
2. Click on item to request craft job
3. Request craft job.
4. ???
5. Crash game

**Expected behavior**
Not to crash.

**Version Information**
 - Minecraft: 1.12.2
 - Forge: 
 - Applied Energistics: AE2 Unofficial Extended Life v0.56.5
 - Thaumcraft: Thaumcraft 6.1.beta26
 - Thaumic Energistics: Thaumic Energistics EL v2.3.3
 - Modpack:MeatballCraft (latest version)

**Logs/Crashlogs**
https://mclo.gs/6TB4rG4

**Comment by Delfayne** [comment]
This is a known issue - caused by an incompatibility when AE2EL was updated. Please upgrade to the latest Thaumic Energistics to fix this issue

**Comment by JathTyki** [comment]
Understood, thanks! There are some other issues that prevent me from upgrading to 2.3.3 I believe it was, so I'll hold out for now.

Appreciate your hard work!
